import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import dynamic from "next/dynamic";
import Footer from "@/components/Footer/Footer";
const Header = dynamic(() => import("@/components/Header/Header"), {
    ssr: false,
});
const inter = Inter({ subsets: ["latin"], display: "swap", weight: ["300", "400", "500", "600", "700", "800"] });

export const metadata: Metadata = {
    title: "Coincapnews",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>
                    <Header />
                    {children}
                    <Footer />
                </Providers>
            </body>
        </html>
    );
}
